### List all messages

## STUDENT REGISTER
POST http://localhost:3001/api/v1/student
content-type: application/json

{
  "name": "Mauricio",
  "lastname": "Anaya",
  "grade_id": 11,
  "email": "mauricio@hotmail.com",
  "user_uuid": "3753ba8f-bb69-4ad9-8741-c1b353843dfe",
  "state_id": 6,
  "city_id": 152,
  "documentype_id": 1,
  "documentnumber": "1007568490",
  "dateofbirth": "2020-08-10"
}